name: PR Checks

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  frontend:
    name: Frontend Checks
    runs-on: ubuntu-latest 
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: 'frontend/package.json'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Lint code
        run: npm run lint

      - name: Run unit tests
        run: npm run test:unit

      - name: Build project
        run: npm run build

  backend:
    name: Backend Checks
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend/insurance
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
        
      - name: Validate Maven project
        run: mvn -B validate -X

      - name: Build with Maven
        run: mvn -B clean -X
      
      - name: Compile
        run: mvn -B compile -X

      - name: Verify
        run: mvn -B verify -X

  docker:
    name: Docker Build & Compose
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Docker Compose (with migrations profile)
        run: docker compose --profile migrations -f docker/docker-compose.yml up -d --build

      - name: Check running containers
        run: docker ps -a

      - name: Stop containers
        if: always()
        run: docker compose -f docker/docker-compose.yml down
